// auto-generated by scripts/generate.py — do not edit

export interface EncodedFrame {
  index: number
  time?: number
  hullVertices?: string
  hullIndices?: string
  waterVertices?: string
  waterIndices?: string
  aeroVertices?: string
  aeroIndices?: string
  mastPoints?: string
  boomPoints?: string
  sailStripVertices?: string
  sailStripIndices?: string
  sailForceOrigins?: string
  sailForceVectors?: string
  foilStripVertices?: string
  foilStripIndices?: string
  foilForceOrigins?: string
  foilForceVectors?: string
  vertices: string
  indices: string
  faceNormals: string
  faceCops: string
  facePressure: string
  position: string
  rotation: string
}

export interface Frame {
  index: number
  time?: number
  hullVertices?: Float32Array
  hullIndices?: Uint32Array
  waterVertices?: Float32Array
  waterIndices?: Uint32Array
  aeroVertices?: Float32Array
  aeroIndices?: Uint32Array
  mastPoints?: Float32Array
  boomPoints?: Float32Array
  sailStripVertices?: Float32Array
  sailStripIndices?: Uint32Array
  sailForceOrigins?: Float32Array
  sailForceVectors?: Float32Array
  foilStripVertices?: Float32Array
  foilStripIndices?: Uint32Array
  foilForceOrigins?: Float32Array
  foilForceVectors?: Float32Array
  vertices: Float32Array
  indices: Uint32Array
  faceNormals: Float32Array
  faceCops: Float32Array
  facePressure: Float32Array
  position: Float32Array
  rotation: Float32Array
}

function decodeF32(b64: string): Float32Array {
  return new Float32Array(Uint8Array.from(atob(b64), c => c.charCodeAt(0)).buffer)
}

function decodeU32(b64: string): Uint32Array {
  return new Uint32Array(Uint8Array.from(atob(b64), c => c.charCodeAt(0)).buffer)
}

export function fromEncoded(d: EncodedFrame): Frame {
  return {
    index: d.index,
    time: d.time,
    hullVertices: d.hullVertices !== undefined ? decodeF32(d.hullVertices) : undefined,
    hullIndices: d.hullIndices !== undefined ? decodeU32(d.hullIndices) : undefined,
    waterVertices: d.waterVertices !== undefined ? decodeF32(d.waterVertices) : undefined,
    waterIndices: d.waterIndices !== undefined ? decodeU32(d.waterIndices) : undefined,
    aeroVertices: d.aeroVertices !== undefined ? decodeF32(d.aeroVertices) : undefined,
    aeroIndices: d.aeroIndices !== undefined ? decodeU32(d.aeroIndices) : undefined,
    mastPoints: d.mastPoints !== undefined ? decodeF32(d.mastPoints) : undefined,
    boomPoints: d.boomPoints !== undefined ? decodeF32(d.boomPoints) : undefined,
    sailStripVertices: d.sailStripVertices !== undefined ? decodeF32(d.sailStripVertices) : undefined,
    sailStripIndices: d.sailStripIndices !== undefined ? decodeU32(d.sailStripIndices) : undefined,
    sailForceOrigins: d.sailForceOrigins !== undefined ? decodeF32(d.sailForceOrigins) : undefined,
    sailForceVectors: d.sailForceVectors !== undefined ? decodeF32(d.sailForceVectors) : undefined,
    foilStripVertices: d.foilStripVertices !== undefined ? decodeF32(d.foilStripVertices) : undefined,
    foilStripIndices: d.foilStripIndices !== undefined ? decodeU32(d.foilStripIndices) : undefined,
    foilForceOrigins: d.foilForceOrigins !== undefined ? decodeF32(d.foilForceOrigins) : undefined,
    foilForceVectors: d.foilForceVectors !== undefined ? decodeF32(d.foilForceVectors) : undefined,
    vertices: decodeF32(d.vertices),
    indices: decodeU32(d.indices),
    faceNormals: decodeF32(d.faceNormals),
    faceCops: decodeF32(d.faceCops),
    facePressure: decodeF32(d.facePressure),
    position: decodeF32(d.position),
    rotation: decodeF32(d.rotation),
  }
}
